 package com.devon1337.RPG.ActiveAbilities;
 
 public enum NFAbilities
 {
   ASSASSINATE, CHARGE, CONFUSION, VANISH, FIREBALL, WRATH, ENTANGLEMENT, BLOOD_SHIELD, SHIELD_SLAM, REJUVENATE, STARFIRE, MOTW, EMPTY;
 }