name: NightFallRPG
main: com.devon1337.RPG.NightFallRPG
version: 0.3.9.0522
api-version: 1.15
author: Devon1337
commands:
   class:
      description: Opens NightFall's classes.
      usage: /<command>
   level:
      description: read/write user level data.
      usage: /<command>
   spellbook:
      description: Opens the spell book.
      usage: /<command>
   roll:
      description: rolls a dice.
      usage: /<command>
   trade:
      description: Trade window.
      usage: /<command>
   nfparty:
      description: Trade window.
      usage: /<command>
   nfquest:
      description: Trade window.
      usage: /<command>
   fl:
      description: Trade window.
      usage: /<command>
   nftest:
      description: Trade window.
      usage: /<command>
   nfprint:
      description: Trade window.
      usage: /<command>
   nflistnpc:
      description: Trade window.
      usage: /<command>
   nfgetdialog:
      description: Trade window.
      usage: /<command>
   nfud:
      description: Trade window.
      usage: /<command>
   nfmsg:
      description: Trade window.
      usage: /<command>
   nfr:
      description: Trade window.
      usage: /<command>
   nftravel:
      description: Trade window.
      usage: /<command>
   nfraid:
      description: Trade window.
      usage: /<command>
   nfinteractwith:
      description: Trade window.
      usage: /<command>