package com.devon1337.RPG.NPC;

public enum NPCCodes {
	// Generic Citizens
	GENERIC_WARRIOR_1, GENERIC_DRUID_1, GENERIC_ROGUE_1,
	GENERIC, PLAYER_MESSAGE, DEPRIVED_INFO, 
	WARRIOR_BLACKWOOD, WARRIOR_HOLDEN, 
	DRUID_LIGHTBREEZE,
	CRAZY_COOT,
	TEST_SHRINE_GOD,
	CARAVAN_TRAVEL;
}
