package com.devon1337.RPG.Utils.Dialog;

public enum DialogCodes {
	
	// DEPRIVED_INFO_#
	DEPRIVED_INFO_1, DEPRIVED_INFO_2, DEPRIVED_INFO_3, DEPRIVED_INFO_4,
	// WARRIOR_QUEST_1_#
	WARRIOR_QUEST_1_1, WARRIOR_QUEST_1_2, WARRIOR_QUEST_1_3,
	// WARRIOR_QUEST_2_#
	WARRIOR_QUEST_2_1, WARRIOR_QUEST_2_2, WARRIOR_QUEST_2_3, WARRIOR_QUEST_2_4,
	WARRIOR_KING_GREETING,
	// WARRIOR_CITIZEN_#_GENERIC_#
	WARRIOR_CITIZEN_1_GENERIC_1, WARRIOR_CITIZEN_1_GENERIC_2, WARRIOR_CITIZEN_1_GENERIC_3, WARRIOR_CITIZEN_1_GENERIC_4,
	WARRIOR_CITIZEN_1_GENERIC_5, WARRIOR_CITIZEN_1_GENERIC_6,
	// DRUID_CITIZEN_#_GENERIC_#
	DRUID_CITIZEN_1_GENERIC_1, DRUID_CITIZEN_1_GENERIC_2, DRUID_CITIZEN_1_GENERIC_3, DRUID_CITIZEN_1_GENERIC_4,
	DRUID_CITIZEN_1_GENERIC_5, DRUID_CITIZEN_1_GENERIC_6,
	HOLDEN_PERRY_GREETING,
	// DRUID_DEFAULTS
	DRUID_TALADAN_GENERIC_FIRE_REMARK, DRUID_TALADAN_GENERIC_SECRETS,
	DRUID_TALADAN_CALLED_FOR,
	// CRAZY_COOT_GENERIC_#
	CRAZY_COOT_GENERIC_1;
	
	
	
	
}
