 package com.devon1337.RPG.Utils.Raycast;
 
 public enum ProjectileType {
   ARROW, DRAGON_FIREBALL, EGG, ENDERPEARL, FIREBALL, FISH_HOOK, LARGE_FIREBALL, LINGERING_POTION, LLAMA_SPIT, SHULKER_BULLET, SIZED_FIREBALL, SMALL_FIREBALL, SNOWBALL, SPECTRAL_ARROW, SPLASH_POTION, THROWABLE_PROJECTILE, THROWN_EXP_BOTTLE, THROWN_POTION, TIPPED_ARROW, TRIDENT, WITHER_SKULL;
 }